CREATE TABLE IF NOT EXISTS player (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  handle TEXT NOT NULL,
  fullname TEXT NOT NULL,
  created TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TEXT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS venue (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  handle TEXT NOT NULL,
  fullname TEXT NOT NULL,
  created TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TEXT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS ruleset (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  handle TEXT NOT NULL,
  fullname TEXT NOT NULL,
  pile INTEGER NOT NULL,
  bonus INTEGER NOT NULL,
  created TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TEXT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS game (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  `date` TEXT NOT NULL,
  seq INTEGER NOT NULL,
  ruleset_id NOT NULL,
  venue_id NOT NULL,
  note TEXT DEFAULT NULL,
  created TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TEXT DEFAULT NULL,
  FOREIGN KEY(ruleset_id) REFERENCES ruleset(id),
  FOREIGN KEY(venue_id) REFERENCES venue(id)
);
CREATE UNIQUE INDEX game_date_seq_ix
  ON game(`date`, seq);

CREATE TABLE IF NOT EXISTS gameplayer (
  game_id INTEGER NOT NULL,
  player_id INTEGER NOT NULL,
  ruleset_id DEFAULT NULL,
  score INTEGER NOT NULL,
  winner BOOLEAN NOT NULL DEFAULT 0,
  created TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TEXT DEFAULT NULL,
  FOREIGN KEY(game_id) REFERENCES game(id),
  FOREIGN KEY(player_id) REFERENCES player(id),
  FOREIGN KEY(ruleset_id) REFERENCES ruleset(id),
  PRIMARY KEY(game_id, player_id)
);
